### ISSUE TITLE
Thoughts on making API more like WebSocket?

### ISSUE THREAD

**Issue by soumya92** [liu-chong/mqtt_crystal#15]
Conceptually MQTT is very similar to Websocket (in fact, MQTT even supports websocket as a protocol).

What do you think about making the API of this library we similar to the Crystal Websocket API (https://crystal-lang.org/api/0.29.0/HTTP/WebSocket.html)?

It would look something like:
- `new(...): Client`: no change
- `on_message(listener: String, String -> )`: similar to websocket.on_message, saves the block to call for each new value
- `publish(topic: String, value: String, qos, retain)`: similar to websocket.send, publishes a single value, and requires that the socket be connected
- `close`: no change, similar to websocket.close.
- `subscribe(topic : String|Array(String))`: sets the subscription topics, but does not actually subscribe.
- `run`: similar to websocket.run, subscribes to the topics and blocks. This would be the run loop. One difference here from regular websocket could be a parameter, e.g. `run(auto_reconnect: Bool)`, that would automatically reconnect, otherwise run would return when the connection is closed.

Is that something you think would be worthwhile?

**Comment by soumya92** [comment]
Actually, it seems WebSocket API is not ideal: https://github.com/crystal-lang/crystal/issues/5600#issue-289450961.

If we use their proposed API, I think we end up with an even nicer solution:

- `new(...): Client`: no change
- `connect`, `reconnect`, `close`: no change 
- `connected?`: no change
- `subscribe(topic : String|Array(String))`: subscribes to the topic(s), similar to current.
- `subscribed?(String): Bool`: since we can have multiple subscriptions, this would check whether a particular topic's suback has been received
- `publish(topic: String, value: String, qos, retain)`: publishes a single value, requires that the client be connected
- `receive: Tuple(String, String)`: blocks until the next value is received, and returns topic and value.

**Comment by lcc-321** [comment]
Yes, it will be great.

**Comment by soumya92** [comment]
Okay sounds good. I'll get something going for a PR soon
